### ISSUE TITLE
1. Use a container for the computational environment

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI_522_Group-11_Save-The-Earth#7]
Hi guys. Please help complete the containization of our environment

**Comment by tonyshumlh** [comment]
Below are the referenced code
```
FROM quay.io/jupyter/minimal-notebook:2023-11-19

COPY environment.yml .
RUN conda env update -f environment.yml
```

**Comment by Jing-19** [comment]
Added docker file!

**Comment by tonyshumlh** [comment]
Hi @Jing-19 @Aishwarya120111 @WeilinHan8 
Not sure the reason, but it seems the work files pushed to Dockerhub is an old version (you can see the notebooks are not merged into one).
For `docker-compose.yml`, you may wanna try the reference code
```
services:
    {ANY_CONTAINER_NAME}:
      image: aish2712/dsci_522_group-11_save-the-earth:a456823
      ports:
        - "8888:8888"
      volumes:
        - .:/home/jovyan/work
      deploy:
        resources:
          limits:
            memory: 5G
      platform: linux/amd64 # For Mac M1/M2 chips
```
